#!/usr/bin/env bash
# Generates agent/livekit.toml from environment variables in agent/.env.
# Usage: bash setup_livekit_toml.sh [env-file]
#
# livekit.toml is gitignored and generated rather than committed, so switching
# projects or agents is an .env edit rather than a source change -- the same
# arrangement as pulseiq-live-kit's scripts/setup_livekit_toml.sh.
#
# Upstream (VisionClaw) deploys this worker to Fly and has no livekit.toml at
# all; both this file and the generated toml are additive, so pulling upstream
# cannot conflict with them.

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="${1:-$HERE/.env}"

if [ -f "$ENV_FILE" ]; then
  set -a && source "$ENV_FILE" && set +a
else
  echo "Warning: $ENV_FILE not found — using existing environment" >&2
fi

if [ -z "${LIVEKIT_PROJECT_SUBDOMAIN:-}" ]; then
  echo "Error: LIVEKIT_PROJECT_SUBDOMAIN not set — cannot generate livekit.toml" >&2
  exit 1
fi

OUT="$HERE/livekit.toml"

if [ -n "${LIVEKIT_AGENT_ID:-}" ]; then
  cat > "$OUT" <<EOF
# Generated by setup_livekit_toml.sh — do not edit; change agent/.env instead.
#
# [agent].id is the deployment's identity. It is unrelated to
# agent_name="corvus-glasses" in main.py, which is what room dispatch targets --
# both must be right, and moving where this runs does not change the name.

[project]
  subdomain = "${LIVEKIT_PROJECT_SUBDOMAIN}"

[agent]
  id = "${LIVEKIT_AGENT_ID}"
EOF
  echo "Generated livekit.toml (subdomain=${LIVEKIT_PROJECT_SUBDOMAIN}, agent=${LIVEKIT_AGENT_ID})"
else
  cat > "$OUT" <<EOF
# Generated by setup_livekit_toml.sh — do not edit; change agent/.env instead.

[project]
  subdomain = "${LIVEKIT_PROJECT_SUBDOMAIN}"
EOF
  echo "Generated livekit.toml (subdomain=${LIVEKIT_PROJECT_SUBDOMAIN}, no agent ID — run 'lk agent create' to bootstrap)"
fi
